[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm install"

[deploy]
startCommand = "cd server && node scripts/init-db.js && NODE_ENV=production node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PORT = "3000"
NODE_ENV = "production"
MYSQLHOST = "${MYSQLHOST}"
MYSQLPORT = "${MYSQLPORT}"
MYSQLUSER = "${MYSQLUSER}"
MYSQLPASSWORD = "${MYSQL_ROOT_PASSWORD}"
MYSQLDATABASE = "${MYSQL_DATABASE}"
