[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm install"

[deploy]
startCommand = "cd server && NODE_ENV=production node scripts/init-db.js && NODE_ENV=production node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.envs]
NODE_ENV = "production"
